package solar_village.leasing_process;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Applicant Name")
   private java.lang.String applicantName;
   @org.kie.api.definition.type.Label(value = "Has HOA")
   private java.lang.Boolean hasHOA;

   public NewOrder()
   {
   }

   public java.lang.String getApplicantName()
   {
      return this.applicantName;
   }

   public void setApplicantName(java.lang.String applicantName)
   {
      this.applicantName = applicantName;
   }

   public java.lang.Boolean getHasHOA()
   {
      return this.hasHOA;
   }

   public void setHasHOA(java.lang.Boolean hasHOA)
   {
      this.hasHOA = hasHOA;
   }

   public NewOrder(java.lang.String applicantName, java.lang.Boolean hasHOA)
   {
      this.applicantName = applicantName;
      this.hasHOA = hasHOA;
   }

}